# Generated by Django 4.1.2 on 2022-12-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentapp', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
