# Generated by Django 4.1.2 on 2022-12-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='zoneimage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tour Image', 'verbose_name_plural': 'Tour Images'},
        ),
    ]
