# Generated by Django 4.1.2 on 2023-02-03 09:56

from django.db import migrations, models
import django.db.models.deletion
import tourapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_favourite_created_at_favourite_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to=tourapp.models.upload_to)),
            ],
            options={
                'verbose_name': 'Tour Image',
                'verbose_name_plural': 'Tour Images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('-created_at',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Zona haqqinda'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tur tarixi'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/type'),
        ),
        migrations.DeleteModel(
            name='ZoneImage',
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour'),
        ),
    ]
