# Generated by Django 4.1.2 on 2023-02-09 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_tourimage_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourapp.tour'),
        ),
    ]
