# Generated by Django 4.1.5 on 2023-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_alter_tourimage_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
