# Generated by Django 4.1.5 on 2023-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
