# Generated by Django 4.2 on 2023-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_alter_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
