# Generated by Django 4.2 on 2023-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
